name: nota_tbs_app
description: Aplikasi input nota timbang TBS via OCR (ML Kit) dengan export Excel per supplier.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_mlkit_text_recognition: ^0.13.0
  image_picker: ^1.1.2
  sqflite: ^2.3.3
  path: ^1.9.0
  path_provider: ^2.1.4
  syncfusion_flutter_xlsio: ^26.2.14
  share_plus: ^10.0.2
  intl: ^0.19.0
  archive: ^3.6.1
  image: ^4.2.0
  crypto: ^3.0.5
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
